local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
local km = vim.keymap

km.set("n", "<leader>i", mark.add_file, { desc = "Add file to harpoon" })
km.set("n", "<leader>fi", ui.toggle_quick_menu, { desc = "Toggle Harpoon [I]nterface" })
km.set("n", "<C-4>", function()
	ui.nav_file(1)
end, { desc = "Navigate to first file" })
km.set("n", "<C-5>", function()
	ui.nav_file(2)
end, { desc = "Navigate to second file" })
km.set("n", "<C-6>", function()
	ui.nav_file(3)
end, { desc = "Navigate to third file" })
km.set("n", "<C-7>", function()
	ui.nav_file(4)
end, { desc = "Navigate to fourth file" })
km.set("n", "<C-8>", function()
	ui.nav_file(5)
end, { desc = "Navigate to fifth file" })
